import { AIColorAdjustments } from '../services/types';
import { PlatformAdapter, PlatformAdjustments } from './platform-adapters';

export interface CaptureOneStyle {
  name: string;
  description?: string;
  adjustments: PlatformAdjustments;
}

/**
 * Generate Capture One style content from AI adjustments
 */
export function generateCaptureOneStyle(
  aiAdjustments: AIColorAdjustments,
  styleName: string,
  description?: string
): string {
  // Use platform adapter to convert AI adjustments to Capture One format
  const adjustments = PlatformAdapter.convertAIAdjustmentsToPlatform(aiAdjustments, 'capture-one');
  
  // Create the XML structure for Capture One style
  const xmlContent = `<?xml version="1.0" encoding="UTF-8"?>
<CaptureOneStyle version="1.0">
  <StyleInfo>
    <Name>${escapeXml(styleName)}</Name>
    <Description>${escapeXml(description || 'Generated by Film Recipe Wizard')}</Description>
    <Created>${new Date().toISOString()}</Created>
    <Author>Film Recipe Wizard</Author>
  </StyleInfo>
  
  <Adjustments>
    ${generateBasicAdjustments(adjustments)}
    ${generateWhiteBalanceAdjustments(adjustments)}
    ${generateToneAdjustments(adjustments)}
    ${generateColorGradingAdjustments(adjustments)}
    ${generateHSLAdjustments(adjustments)}
    ${generateGrainAdjustments(adjustments)}
    ${generateVignetteAdjustments(adjustments)}
    ${generateClarityAdjustments(adjustments)}
    ${generateStructureAdjustments(adjustments)}
  </Adjustments>
</CaptureOneStyle>`;

  return xmlContent;
}

/**
 * Generate structure adjustments XML (Capture One specific)
 */
function generateStructureAdjustments(adjustments: PlatformAdjustments): string {
  if (adjustments.platformSpecific?.captureOne?.structure === undefined) return '';
  
  return `    <Structure>${adjustments.platformSpecific.captureOne.structure}</Structure>`;
}

/**
 * Generate basic adjustments XML
 */
function generateBasicAdjustments(adjustments: PlatformAdjustments): string {
  const parts: string[] = [];
  
  if (adjustments.exposure !== undefined) {
    parts.push(`    <Exposure>${adjustments.exposure}</Exposure>`);
  }
  
  if (adjustments.contrast !== undefined) {
    parts.push(`    <Contrast>${adjustments.contrast}</Contrast>`);
  }
  
  if (adjustments.saturation !== undefined) {
    parts.push(`    <Saturation>${adjustments.saturation}</Saturation>`);
  }
  
  if (adjustments.vibrance !== undefined) {
    parts.push(`    <Vibrance>${adjustments.vibrance}</Vibrance>`);
  }
  
  return parts.join('\n');
}

/**
 * Generate white balance adjustments XML
 */
function generateWhiteBalanceAdjustments(adjustments: PlatformAdjustments): string {
  const parts: string[] = [];
  
  if (adjustments.temperature !== undefined || adjustments.tint !== undefined) {
    parts.push('    <WhiteBalance>');
    if (adjustments.temperature !== undefined) {
      parts.push(`      <Temperature>${adjustments.temperature}</Temperature>`);
    }
    if (adjustments.tint !== undefined) {
      parts.push(`      <Tint>${adjustments.tint}</Tint>`);
    }
    parts.push('    </WhiteBalance>');
  }
  
  return parts.join('\n');
}

/**
 * Generate tone adjustments XML
 */
function generateToneAdjustments(adjustments: PlatformAdjustments): string {
  const parts: string[] = [];
  
  if (adjustments.highlights !== undefined || 
      adjustments.shadows !== undefined || 
      adjustments.whites !== undefined || 
      adjustments.blacks !== undefined) {
    parts.push('    <ToneMapping>');
    if (adjustments.highlights !== undefined) {
      parts.push(`      <Highlights>${adjustments.highlights}</Highlights>`);
    }
    if (adjustments.shadows !== undefined) {
      parts.push(`      <Shadows>${adjustments.shadows}</Shadows>`);
    }
    if (adjustments.whites !== undefined) {
      parts.push(`      <Whites>${adjustments.whites}</Whites>`);
    }
    if (adjustments.blacks !== undefined) {
      parts.push(`      <Blacks>${adjustments.blacks}</Blacks>`);
    }
    parts.push('    </ToneMapping>');
  }
  
  return parts.join('\n');
}

/**
 * Generate color grading adjustments XML
 */
function generateColorGradingAdjustments(adjustments: PlatformAdjustments): string {
  const colorGrading = adjustments.platformSpecific?.captureOne?.colorGrading;
  if (!colorGrading) return '';
  
  const parts: string[] = [];
  parts.push('    <ColorGrading>');
  
  if (colorGrading.shadows) {
    parts.push('      <Shadows>');
    if (colorGrading.shadows.hue !== undefined) {
      parts.push(`        <Hue>${colorGrading.shadows.hue}</Hue>`);
    }
    if (colorGrading.shadows.saturation !== undefined) {
      parts.push(`        <Saturation>${colorGrading.shadows.saturation}</Saturation>`);
    }
    if (colorGrading.shadows.lightness !== undefined) {
      parts.push(`        <Lightness>${colorGrading.shadows.lightness}</Lightness>`);
    }
    parts.push('      </Shadows>');
  }
  
  if (colorGrading.midtones) {
    parts.push('      <Midtones>');
    if (colorGrading.midtones.hue !== undefined) {
      parts.push(`        <Hue>${colorGrading.midtones.hue}</Hue>`);
    }
    if (colorGrading.midtones.saturation !== undefined) {
      parts.push(`        <Saturation>${colorGrading.midtones.saturation}</Saturation>`);
    }
    if (colorGrading.midtones.lightness !== undefined) {
      parts.push(`        <Lightness>${colorGrading.midtones.lightness}</Lightness>`);
    }
    parts.push('      </Midtones>');
  }
  
  if (colorGrading.highlights) {
    parts.push('      <Highlights>');
    if (colorGrading.highlights.hue !== undefined) {
      parts.push(`        <Hue>${colorGrading.highlights.hue}</Hue>`);
    }
    if (colorGrading.highlights.saturation !== undefined) {
      parts.push(`        <Saturation>${colorGrading.highlights.saturation}</Saturation>`);
    }
    if (colorGrading.highlights.lightness !== undefined) {
      parts.push(`        <Lightness>${colorGrading.highlights.lightness}</Lightness>`);
    }
    parts.push('      </Highlights>');
  }
  
  parts.push('    </ColorGrading>');
  return parts.join('\n');
}

/**
 * Generate HSL adjustments XML
 */
function generateHSLAdjustments(adjustments: PlatformAdjustments): string {
  const hsl = adjustments.platformSpecific?.captureOne?.hsl;
  if (!hsl) return '';
  
  const parts: string[] = [];
  parts.push('    <HSL>');
  
  const colors = ['red', 'orange', 'yellow', 'green', 'aqua', 'blue', 'purple', 'magenta'];
  colors.forEach(color => {
    const colorAdjustments = (hsl as any)[color];
    if (colorAdjustments) {
      parts.push(`      <${color.charAt(0).toUpperCase() + color.slice(1)}>`);
      if (colorAdjustments.hue !== undefined) {
        parts.push(`        <Hue>${colorAdjustments.hue}</Hue>`);
      }
      if (colorAdjustments.saturation !== undefined) {
        parts.push(`        <Saturation>${colorAdjustments.saturation}</Saturation>`);
      }
      if (colorAdjustments.lightness !== undefined) {
        parts.push(`        <Lightness>${colorAdjustments.lightness}</Lightness>`);
      }
      parts.push(`      </${color.charAt(0).toUpperCase() + color.slice(1)}>`);
    }
  });
  
  parts.push('    </HSL>');
  return parts.join('\n');
}

/**
 * Generate grain adjustments XML
 */
function generateGrainAdjustments(adjustments: PlatformAdjustments): string {
  const grain = adjustments.platformSpecific?.captureOne?.grain;
  if (!grain) return '';
  
  const parts: string[] = [];
  parts.push('    <Grain>');
  if (grain.amount !== undefined) {
    parts.push(`      <Amount>${grain.amount}</Amount>`);
  }
  if (grain.size !== undefined) {
    parts.push(`      <Size>${grain.size}</Size>`);
  }
  if (grain.roughness !== undefined) {
    parts.push(`      <Roughness>${grain.roughness}</Roughness>`);
  }
  parts.push('    </Grain>');
  return parts.join('\n');
}

/**
 * Generate vignette adjustments XML
 */
function generateVignetteAdjustments(adjustments: PlatformAdjustments): string {
  const vignette = adjustments.platformSpecific?.captureOne?.vignette;
  if (!vignette) return '';
  
  const parts: string[] = [];
  parts.push('    <Vignette>');
  if (vignette.amount !== undefined) {
    parts.push(`      <Amount>${vignette.amount}</Amount>`);
  }
  if (vignette.midpoint !== undefined) {
    parts.push(`      <Midpoint>${vignette.midpoint}</Midpoint>`);
  }
  if (vignette.roundness !== undefined) {
    parts.push(`      <Roundness>${vignette.roundness}</Roundness>`);
  }
  if (vignette.feather !== undefined) {
    parts.push(`      <Feather>${vignette.feather}</Feather>`);
  }
  parts.push('    </Vignette>');
  return parts.join('\n');
}

/**
 * Generate clarity adjustments XML
 */
function generateClarityAdjustments(adjustments: PlatformAdjustments): string {
  if (adjustments.clarity === undefined) return '';
  
  return `    <Clarity>${adjustments.clarity}</Clarity>`;
}

/**
 * Escape XML special characters
 */
function escapeXml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}
